### ISSUE TITLE
Babelyoda chokes on CFBundleDisplayName in InfoPlist.strings

### ISSUE THREAD

**Issue by rbsgn** [eploko/babelyoda#1]
It is completely eligible to add following lines to your InfoPlist.strings file:

```
/* Localized app name for iOS home screen */
CFBundleDisplayName = "My l10n app";
```

Both iOS and OS X recognizes such a text and handle them correctly. However Babelyoda fails with pretty obscure error message while trying to process this file.

I think Babelyoda should support this type of text and handle it correctly.

**Comment by eploko** [comment]
Closing as the project is being archived.
