### ISSUE TITLE
Ability to push all the existing localizations to Tanker

### ISSUE THREAD

**Issue by rbsgn** [eploko/babelyoda#3]
This issue is valid when you try to add Babelyoda support to your existing project with localized resources. You have localized strings files, XIBs and so on. When you first tries to run Babelyoda she destroys all the existing strings files and replaces them with genstrings output. It is pretty rude :) 

It would be nice if Babelyoda offered to import initial translations (if any exist — strings & XIBs) to Tanker on first run in order to save hours of previous work on localization.

**Comment by eploko** [comment]
Closing as the project is being archived.
